### ISSUE TITLE
Ridge plot

### ISSUE THREAD

**Issue by jtrakk** [MakieOrg/AlgebraOfGraphics.jl#127]
![image](https://user-images.githubusercontent.com/43392409/99893831-e3678300-2c36-11eb-8206-74d904d1a179.png)

**Comment by jkrumbiegel** [comment]
Not the prettiest solution but you can do this

```julia
data((; val = randn(1000), groups = rand(["Fair", "Good", "Very Good", "Premium", "Ideal"], 1000))) *
    mapping(:groups, :val) *
    visual(Violin, orientation = :horizontal, side = :left, strokewidth = 1, color = :gray70) |>
    draw(scales(Y = (; palette = xs -> range(0, 1, length = length(xs)))), axis = (; yreversed = true))
```
<img width="584" alt="image" src="https://github.com/user-attachments/assets/6284d7c3-4c29-4115-9c11-16e83ee6570a">

Closing this, if further needs arise, please open a new issue for that.
