### ISSUE TITLE
cornerplot and corrplot

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/AlgebraOfGraphics.jl#210]
Any plans to add cornerplot and corrplot like in StatsPlots.jl? Perhaps it is already possible to achive similar result with AOG?

**Comment by piever** [comment]
Something like

```julia
df = (x = rand(100), y = rand(100), z = rand(100))
vars = [:x, :y, :z]
data(df) * (visual(Scatter) + linear()) * mapping([:x, :y, :z], [:x :y :z], col = dims(1), row = dims(2)) 
```

would do a "symmetric" `corrplot`. It's definitely planned to have the full `corrplot` functionality available, but the interface / implementation are not super clear. See also #187 and https://github.com/piever/SplitApplyPlot.jl/issues/53#issuecomment-831144023

**Comment by juliohm** [comment]
@piever can you please clarify the col/row mechanism? Couldn't find it in the docs. I am having trouble creating the corner/corrplot using the snippet you shared above.

**Comment by filchristou** [comment]
I am also having some trouble undestanding how does this `col`, `row`, `dims` mechanism work.
In your example your diagonal will be just a straight line.
![image](https://user-images.githubusercontent.com/27723218/171846213-960e9765-9182-4af4-ba8e-c54297fad050.png)

is there a way to substitute the diagonal plots with the density functions instead ?
![image](https://user-images.githubusercontent.com/27723218/171846303-ea1e5f47-3300-4ace-a643-22c4eb2b2fa3.png)

**Comment by sethaxen** [comment]
> Something like
> 
> ```julia
> df = (x = rand(100), y = rand(100), z = rand(100))
> vars = [:x, :y, :z]
> data(df) * (visual(Scatter) + linear()) * mapping([:x, :y, :z], [:x :y :z], col = dims(1), row = dims(2)) 
> ```
> 
> would do a "symmetric" `corrplot`.

@piever I have data in `x` and would like to split `x` by a categorical cycling variable `group`, plotting a 4x4 corner plot where subplot `(i, j)` compares x-values of group `i` with x-values of group `j`. Can this example be modified for something like this? e.g. data

```julia
df = (x = rand(100), group=repeat(1:4, 25))
```

**Comment by sethaxen** [comment]
> I think something like
> 
> ```julia
> data(df) * (visual(Scatter) + linear()) * mapping(:x, :x, col = :group => nonnumeric, row = :group => nonnumeric)
> ```
> 
> should do the trick in that case.

This doesn't seem to:
![tmp](https://user-images.githubusercontent.com/8673634/176283511-736d629f-91c2-4a5f-858d-cc544db99f25.png)

**Comment by piever** [comment]
Ah yes, of course you are right... I'm afraid there is no way at the moment other than manually unstacking the data to pass to the wide format.

**Comment by pkofod** [comment]
Is this something you would be interested in adding as a feature? And have you already thought about the "AoG" interface for such a thing? Or do you think it should just be a Makie recipe with DataFrame input because it can't really leverage any AoG features?

**Comment by juliohm** [comment]
Update: PairPlots.jl provides this functionality with Makie.jl

Em ter., 19 de set. de 2023 03:06, Patrick Kofod Mogensen <
***@***.***> escreveu:
