### ISSUE TITLE
band plot gives artifact

### ISSUE THREAD

**Issue by tbenst** [MakieOrg/AlgebraOfGraphics.jl#269]
```julia
Xs = repeat(collect(1:100), 10)
Ys = sin.(Xs) + randn(1000)*0.2
df = DataFrame(x=Xs, y=Ys)
df = transform(groupby(df, ["x"]),
    "y" => mean, "y" => minimum, "y" => maximum)
data(df) * mapping(:x, :y_minimum, :y_maximum) * visual(Band) |> draw
```

![image](https://user-images.githubusercontent.com/863327/130538459-2aa71e4e-8d3e-42c2-8ba0-38c2e99e5dd7.png)

**Comment by jkrumbiegel** [comment]
This is in the nature of the data you prepared, your x values loop back to 1 after reaching 100. If you sort or filter the data, the problem goes away.

**Comment by tbenst** [comment]
oh! transform didn't do what i expected. this works :)
```
using AlgebraOfGraphics, DataFrames, StatsBase, CairoMakie
Xs = repeat(collect(1:100), 10)
Ys = sin.(Xs) + randn(1000)*0.2
df = DataFrame(x=Xs, y=Ys)
df = transform(groupby(df, ["x"]),
    "y" => mean, "y" => minimum, "y" => maximum)[1:100,:]
data(df) * mapping(:x, :y_minimum, :y_maximum) * visual(Band) |> draw
```
<img width="573" alt="image" src="https://github.com/user-attachments/assets/ce48b15b-46f5-4e6e-b237-c0200bf2cad5">
