### ISSUE TITLE
handling missing values

### ISSUE THREAD

**Issue by mkborregaard** [MakieOrg/AlgebraOfGraphics.jl#297]
AlgebraOfGraphics don't seem to handle missing values the same as Makie. Consider
![Screenshot 2021-10-15 at 11 03 44](https://user-images.githubusercontent.com/8429802/137486117-f09a07b9-b7f8-4bae-a75c-d78d76a96fe1.png)

Using `dropmissing` on the full DataFrame is not viable, as the missings are likely to be in columns you don't use. A workaround is
```julia
data(dropmissing(allison, [:BodyWt, :Gestation])) *
	mapping(:BodyWt, :Gestation) |> 
        draw
```
but I believe you would expect AoG to handle missing like Makie (and it would be more user friendly - the current behaviour seems like a bug.)

**Comment by jariji** [comment]
I would rather get an error and pass `skipmissing=true` where needed rather than have incomplete and misleading results by default. Maybe there could even be a functional "preprocessing" API similar to the Analysis API which would allow transforming the data prior to plotting.

```jl
data(d) * preprocess(dropmissing) * ...
```
