### ISSUE TITLE
Pagination of large facet plots

### ISSUE THREAD

**Issue by MichaelHatherly** [MakieOrg/AlgebraOfGraphics.jl#303]
When faceting a plot over a large number of columns/rows (or just wrapping with `layout`) the size of the plots can sometimes become quite unwieldy and requires manual intervention to increase the figure size or shrink the font size. Something that's a nice feature to have is pagination of faceted plots to reduce the amount of of axes that appear per-figure. There's a couple of options to do this with ggplot2: `ggforce` and `gridExtra` can handle this.

The basic look of the API is instead of writing this:

```julia
layer = data(df) * mapping(:id, :wt; layout = :dose => nonnumeric)
draw(layer)
```

![image](https://user-images.githubusercontent.com/6144086/139053939-252a8fab-8a42-406a-ba82-4c1f3ae2c12a.png)

we wrap the `Layer` with `paginate`:

```julia
draw(
	paginate(
		layer;
		limit = 4
	)
)
```

![image](https://user-images.githubusercontent.com/6144086/139054402-c6d532ab-8f7b-44a6-9d00-32699fcd8e56.png)

which just partitions the `.data` contained in the `Layer` based on what's used in `layout` (or `row` and `col`).

If there's interest in upstreaming this I'm happy to sort that out. Pagination has come in handy for a lot of our plotting needs in Pumas so I figured it may be more generally useful.

**Comment by jkrumbiegel** [comment]
pagination has existed for a while now
