### ISSUE TITLE
markersize do not create a legend

### ISSUE THREAD

**Issue by diegozea** [MakieOrg/AlgebraOfGraphics.jl#306]
Hi!

I have just noticed that `markersize` does not create a legend. 

![image](https://user-images.githubusercontent.com/2822757/141524387-0901c865-a058-47c1-b4a5-271297939550.png)

Code example:

```julia
using RDatasets, AlgebraOfGraphics, CairoMakie
set_aog_theme!()
iris = dataset("datasets", "iris")
plt = data(iris) * mapping(:PetalWidth, :PetalLength, markersize=:SepalLength) * visual(Scatter)
draw(plt)
```

Cheers,

**Comment by jkrumbiegel** [comment]
This is fixed
