### ISSUE TITLE
How to apply the pair syntax?

### ISSUE THREAD

**Issue by bardo84** [MakieOrg/AlgebraOfGraphics.jl#310]
Re https://discourse.julialang.org/t/algebraofgraphics-question/72982

To name axes or legends in this format you would use the pair syntax, that is `x => "x"` , `y => "y"` , `grp => "group"` .

How to apply the pair syntax?
```data(df) * mapping(:bill_length_mm => (t -> t / 10) => "bill length (cm)")```
appears again for the other `data(df)` form. (How can I understand this syntax though?)
I tried some possible places.
VSCode flags where the syntax is obviously wrong, other locations give run-time errors.
I searched but could not find code with `=>` in the tutorial or gallery examples.

**Comment by jkrumbiegel** [comment]
Closing as outdated, there are many places with pair syntax in the docs now
