### ISSUE TITLE
Function to manage plot title?

### ISSUE THREAD

**Issue by kir0ul** [MakieOrg/AlgebraOfGraphics.jl#331]
It would be nice to have the option to add or change the main title of the plot, something like [`ggtitle`](https://r-charts.com/ggplot2/titles/) in `ggplot2` or like the [title property](https://vega.github.io/vega-lite/docs/title.html) in Vega-Lite. I believe there's no official way to do this yet or at least I couldn't find anything in the docs.

Thanks for this awesome package!

**Comment by knuesel** [comment]
With the `axis` keyword you can pass options to Makie's [Axis](https://makie.juliaplots.org/v0.15.2/documentation/api_reference/#Axis) object, which includes a `title` option, so you can write `draw(..., axis=(; title="My title"))`.

**Comment by greimel** [comment]
This, however, will not work together with faceting. There should be such an option that works even when faceting.

**Comment by RomeoV** [comment]
I also ran into the issue with faceting.
It's not a great solution, but you can add your own Label like so:
```julia
plt = draw(...)  # suppose this has two columns.
Makie.Label(plt.figure[0, 1:2], "Title text";
            fontsize=20, font=:bold)
```
