### ISSUE TITLE
Subplots layoute

### ISSUE THREAD

**Issue by FedeClaudi** [MakieOrg/AlgebraOfGraphics.jl#382]
## Problem description
I'm not sure if AoG is the right place to do this or if it should be part of Makie or even a separate package.

Matplotlib (and gg plot in R I think) has [this feature](https://matplotlib.org/3.5.0/tutorials/provisional/mosaic.html#string-short-hand) where you can pass a string specifying a figure layout:

```python
mosaic = """
    AB
    CD
    """
fig = plt.figure()
axes = fig.subplot_mosaic(mosaic)
```

gives a figure with 4 subplots and changing mosaic e.g. to:
```python
mosaic = ""'
AAABB
AAACC
"""
```
can be used to create more complicated layouts. 

It's a very convenient way to specify a figure layout, it would be great to have something similar in Julia

**Comment by jkrumbiegel** [comment]
Could be useful for Makie, closing this for out of scope for AoG. We generally only have the wrapped or row/col facet layout here
