### ISSUE TITLE
[FR] Plot legend when plotting into existing figure

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/AlgebraOfGraphics.jl#394]
When drawing a plot directly, I get this neat legend.
<img width="374" alt="image" src="https://user-images.githubusercontent.com/61620837/169661353-4758520c-cd6e-4e59-a726-03a0079f1c0c.png">

But when plotting into an existing figure, I am completely unable to figure out how to still plot the legend:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/61620837/169661374-7fe87884-9f3f-401e-aa9d-a79b48483fed.png">

A potential solution could be to make a grid inside the position being plotted into that contains both the axis and the legend.

**Comment by musoke** [comment]
[legend!](https://aog.makie.org/stable/API/functions/#AlgebraOfGraphics.legend!) will do this for you.  

Something like 

```
legend!(fig, draw!_output)
```

**Comment by icweaver** [comment]
Yep, more info here and here

https://aog.makie.org/stable/API/functions/#AlgebraOfGraphics.draw

https://aog.makie.org/stable/layers/draw/

**Comment by musoke** [comment]
Is there a way to position a legend created with `legend!`?  Say for example I want to place a legend in the top right of the plot in your example.  The obvious way to try is placing it in `fig[1, 1]` and using the `halign` and `valign` args to `lengend!`:

```
using AlgebraOfGraphics, CairoMakie, DataFramesMeta
set_aog_theme!()

df = DataFrame(x1=1:10, x2=sin.(1:10), grp=sign.(cos.(1:10)))

fig = Figure()
ax = Axis(fig[1, 1]; xlabel="x1", ylabel="y1")

plt = data(df) * mapping(:x1, :x2; color=:grp => nonnumeric => "Group")

grid = draw!(ax, plt)

hlines!(ax, [0.2, 0.6]; color=:black)

legend!(fig[1, 1], grid; halign=:right, valign=:top)

fig
```

However, this ends up shrinking the x dimension of the axis to match the size of the legend:

![image](https://user-images.githubusercontent.com/16665084/197916859-64bb1375-6c45-4f30-aa66-700783c5dbce.png)

**Comment by jkrumbiegel** [comment]
Try passing `tellheight = false, tellwidth = false` as well to avoid the shrinking. In base Makie, the `axislegend` function is there to make putting a legend inside an Axis more convenient.

**Comment by musoke** [comment]
That's exactly what I needed, thanks @jkrumbiegel!  Would it be helpful for me to submit a PR adding these examples in the docs?

**Comment by piever** [comment]
Doc PRs are always welcome! I imagine that would belong in the [legend tweaking](https://aog.makie.org/dev/gallery/gallery/customization/legend/#Legend-tweaking) section.

Maybe we should add `axislegend!` that mimics `axislegend`. It might make sense to add `axislegend!` (same as `legend!`, but it calls `axislegend` instead of `Legend` at the end) and document that instead.

**Comment by KronosTheLate** [comment]
Thanks for the help, much appreciated! ^_^
