### ISSUE TITLE
Change `mapping` keyword from `col` to `column`

### ISSUE THREAD

**Issue by CameronBieganek** [MakieOrg/AlgebraOfGraphics.jl#405]
I frequently misread the `col` keyword argument to `mapping` as "color". In the context of plotting, `"col" = "color"` springs to mind much more readily than `"col" = "column"`. In addition, R plots use the `col` keyword for "color":

https://bookdown.org/rdpeng/exdata/plotting-and-color-in-r.html

So anyone coming from R is likely to be confused.

**Comment by jkrumbiegel** [comment]
I'm sympathetic to the cause, but I don't think it's worth the breaking change at this point, so I'm going to close this as not planned
