### ISSUE TITLE
How can I hide the legend title? 

### ISSUE THREAD

**Issue by zdlspace0528** [MakieOrg/AlgebraOfGraphics.jl#422]
Dear all,

When I use AlgebraOfGraphics.jl, How can I hide the legend title? Here is an example.

using RDatasets, AlgebraOfGraphics, CairoMakie
df = dataset("datasets", "iris")
plt = data(df) * mapping(:Species, :SepalLength, color = :Species) * visual(Violin)
fg = draw(plt; legend = (position = :bottom, titlevisible = false, framevisible = false))
<img width="403" alt="截屏2022-08-08 22 46 58" src="https://user-images.githubusercontent.com/75175622/183449929-a220921e-298e-4f29-b0a3-c46b11d0dae8.png">
How can I hide the legend title “Species”? I try to use titlevisible = false, but it does not work.

**Comment by greimel** [comment]
Try `color = :Species => ""` and then probably `legend = (; titleposition = :left)` in `draw`.

**Comment by jkrumbiegel** [comment]
With 0.7 onwards you can also set a label in the `scales`

```julia
df = DataFrame(
    SepalLength = randn(300) .* repeat([1, 2, 3], inner = 100),
    Species = repeat(["Setosa", "Versicolor", "Virginica"], inner = 100),
)

plt = data(df) * mapping(:Species, :SepalLength, color = :Species) * visual(Violin)
fg = draw(plt, scales(Color = (; label = "")); legend = (position = :bottom, titlevisible = false, framevisible = false))
```

<img width="573" alt="image" src="https://github.com/user-attachments/assets/0c6c75d3-b4c3-4ae5-9390-863d0ce02b98">
