### ISSUE TITLE
SnoopPrecompile

### ISSUE THREAD

**Issue by carstenbauer** [MakieOrg/AlgebraOfGraphics.jl#430]
Came up in [this discourse thread](https://discourse.julialang.org/t/very-slow-time-to-first-plot-2022/88968/48). AOG doesn't have snoop-precompile statements (i.e. a typical workflow script as part of precompilation) which is why generating a system image containing it doesn't give the desired (and possible) speedups. Please consider using SnoopPrecompile! It might also improve TTFX without system images 😉 

(See e.g. OrdinaryDiffEq for an example: https://github.com/SciML/OrdinaryDiffEq.jl/blob/v6.27.1/src/OrdinaryDiffEq.jl#L207-L333)

**Comment by greimel** [comment]
I did some timings on this Julia branch https://github.com/JuliaLang/julia/pull/47184 _without_ system image.

CairoMakie's TTFP takes 14.9 seconds, while AoG takes 17.7 seconds. So there are around three seconds on the table (once that Julia PR gets merged)

```julia
begin
    t = time()
    using CairoMakie
    @info time() - t
    fig = scatter(rand(10))
    @info time() - t
    save("/tmp/test.pdf", fig)
    @info time() - t
end
[ Info: 8.163447856903076
[ Info: 12.862381935119629
[ Info: 14.932760000228882
```

```julia
begin 
       t = time()
       using AlgebraOfGraphics, CairoMakie
       @info time() - t
       fig = data(df(100)) * mapping(:x, :y) * visual(Scatter) |> draw
       @info time() - t
       save("/tmp/aog.pdf", fig)
       @info time() - t
end
[ Info: 0.0011899471282958984
[ Info: 16.021846055984497
[ Info: 17.706539154052734
```
