### ISSUE TITLE
Legend doesn't properly show linestyle

### ISSUE THREAD

**Issue by jonas-schulze** [MakieOrg/AlgebraOfGraphics.jl#435]
Instead of showing the line styles, it just shows gray blobs:

```julia
using AlgebraOfGraphics # v0.6.11
using CairoMakie # v0.8.13

x = 1:3
y = 'a':'c'
df = (; x, y)
plt = data(df) * mapping(:x, linestyle=:y) * visual(VLines)

fg = draw(plt)
save("mwe.png", fg)
```

![mwe](https://user-images.githubusercontent.com/8181318/199923521-3c52084a-18d7-4922-a400-6c5a96aa330b.png)

The behavior is the same for AlgebraOfGraphics `v0.6.12` and CairoMakie `v0.9.2`.

**Comment by skleinbo** [comment]
Same with e.g. `ScatterLines`. The appropriate recipes need to be added to [src/guides/legendelements.jl](https://github.com/MakieOrg/AlgebraOfGraphics.jl/blob/a8ed81c7997ee9e01e7c53097d6bc25b69666bde/src/guides/legendelements.jl)
