### ISSUE TITLE
A simpler way to plot heatmaps with independent colorbars

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/AlgebraOfGraphics.jl#444]
The following kinda works?

```Julia
using GLMakie, DataFrames, AlgebraOfGraphics
df = DataFrame(;
    x = repeat(repeat(1:10, inner=10), outer =2),
    y = repeat(repeat(1:10, outer =10), outer =2),
    val= rand(200),
    l = [fill("a", 100)..., fill("b",100)...])

data(df) * mapping(:x, :y, :val, layout=:l) * visual(Heatmap) |> draw
```
<img width="395" alt="Screenshot 2023-02-06 at 23 10 49" src="https://user-images.githubusercontent.com/19525261/217099070-b1018a34-d994-4de1-acf3-9db4d0c24cff.png">

but, 
1. it will be nice if there were a simpler way to pass the data. 
2. each heatmap could have his own 
     -colobar
     -colormap
     -colorrange
so that we could control the appearance for different variables (a & b here).

**Comment by mscott99** [comment]
Thanks for that code, I was trying to figure out how to display a heatmap from a 2d array.

It seems to me that a single colorbar is preferable by default.

**Comment by jkrumbiegel** [comment]
Closing the specific request for independent color bars for different values of a grouping variable as not planned. The new scales system would allow you two use different color scales if you had different factors, but there isn't support for adding those multiple colorbars yet (that's a different issue, though).
