### ISSUE TITLE
Wrapping AoG in Tidier.jl to expose a more 1:1 ggplot interface

### ISSUE THREAD

**Issue by kdpsingh** [MakieOrg/AlgebraOfGraphics.jl#448]
Dear AoG package maintainers,

I have recently been working on a package Tidier.jl that aims to bring an R tidyverse-like API to Julia. Here's a link to the package: https://github.com/kdpsingh/Tidier.jl. The package is written using macros and serves as syntactic sugar on top of a DataFrames.jl backend, converting R-like expressions into valid DataFrames.jl code.

At some point, I would like to similarly bring a ggplot2-like interface to the package, again using macros to create an R-like feel. The idea would be that we would replicate R ggplot2 syntax rather than try to diverge from it.

Although we originally considered using Gadfly as a backend for this effort, many folks have suggested we consider AoG instead because Makie is more actively maintained.

I wanted to make sure your team was okay with our wrapping AoG for this effort. I didn't want to step on any toes and wanted to do this in partnership to respect the amazing work you've done. My intent would be to credit AlgebraOfGraphics on our README and on our documentation.

I wouldn't need anything from you. Just wanted to check and make sure this is okay from your standpoint.

Here's our issue tracking this development: https://github.com/kdpsingh/Tidier.jl/issues/66

I appreciate your consideration,

Karandeep

**Comment by kdpsingh** [comment]
I'll go ahead and close this issue. If you have any questions or concerns, feel free to reach out to me or post an issue on the Tidier.jl repo. Thank you.

**Comment by SimonDanisch** [comment]
Hi, I'm only co-maintainer, but I'm really excited about this! Feel free to ask me any questions, I may not be able to answer them but I definitely hope that this succeeds :)

**Comment by kdpsingh** [comment]
Thanks @SimonDanisch! We will keep you posted and will reach out if questions!

**Comment by piever** [comment]
Hey! Thank you for such a thoughtful introduction.

I think it is a really nice project: many users are used to the R syntax. In my view algebra of graphics is a distinct project from ggplot (both in terms of design choices and surface syntax), but it should have most of the machinery you need to build a ggplot syntax layer on top of it. It could even be nice to make some sort of "cheat sheet" at the end to show how to convert from one syntax to the other.

Of course, if something is unclear feel free to ask! I confess I am not super responsive in this period, but I'll do my best to be of help.

Good luck!

**Comment by kdpsingh** [comment]
Thanks! Yes, I really *like* that AoG has made design choices thoughtfully that reflect the Julian context (e.g., ability to use a combination of multiplication and addition to compose plots).

I agree that I think the machinery is there within AoG to expose a ggplot-like syntax and may even serve as a stepping stone to people using AoG directly.

I plan to add a few other data-frame-oriented features to Tidier.jl then will come back to plotting shortly afterwards.

Thanks again!
