### ISSUE TITLE
Legend doesn't show color in docs example

### ISSUE THREAD

**Issue by jariji** [MakieOrg/AlgebraOfGraphics.jl#450]
v0.6.14 
https://aog.makie.org/stable/gallery/gallery/scales/custom_scales/

The legend is just black boxes, no colors

![image](https://user-images.githubusercontent.com/96840304/228365071-e3ff5356-6f66-454e-9907-039157c553cc.png)

**Comment by jkrumbiegel** [comment]
This is correct now
