### ISSUE TITLE
Many attributes to `visual` don't have any effect

### ISSUE THREAD

**Issue by roland-KA** [MakieOrg/AlgebraOfGraphics.jl#454]
The AoG documentation states (https://aog.makie.org/stable/generated/visual/) that the Makie-attributes can be passed to `visual`. E.g. `visual(BarPlot)` may be enhanced with: `visual(BarPlot; width = 0.8)` to specify the width of the bars.

This works with some attributes like `width`. But I have also tried attributes like `label_offset`, `label_size` and `label_rotation` on a bar plot. Non of them had any effect.

Does AoG only support a subset of the Makie-attributes or is this a bug?

**Comment by jkrumbiegel** [comment]
These should just get forwarded, I tried your examples and they worked so I'll close this. Makie also complains these days when you pass it invalid keyword arguments in case that ever was the problem

```julia
mapping(1:5, 1:5) * visual(BarPlot, bar_labels = :y, label_offset = -50, label_size = 50) |> draw
```

<img width="592" alt="image" src="https://github.com/user-attachments/assets/7676d50d-d6e8-4fe0-9811-51b34602c907">
