### ISSUE TITLE
MakieCon feedback

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/AlgebraOfGraphics.jl#457]
Maybe include here all the feedback provided during makiecon, so we can have a clear idea of what is already possible and what is not.

@piever ?

**Comment by piever** [comment]
Hey, yes, that's a good idea, I plan to go through my notes and upload them here next week.

**Comment by piever** [comment]
So, with some order, here is the actionable MakieCon feedback.

## Usability issues

It seems that most of the problems were linked to legends and labelling.

- [ ] Provide helpers for customizability (mix and match with existing Makie legends)
- [ ] Legends does not adjust completely to style used (cf. #228)
- [ ] Easier renaming (when using wide data or pregrouped data things are clumsy, it may be tricky to remove some names as well)

## Data processing

- [ ] Provide extensibility mechanism for custom analyses (worked at during hackathon, but still wip). At the moment only possible by "copying" the source code for existing analyses.

## Documentation issues

- [ ] Philosophy first approach. Iinsist more on philosophy on the documentation, it seems easy to end up "using AoG the wrong way", which can be frustrating.
- [ ] Insist on possibility of creating first "draft" of plot with AoG and then tweaking with Makie (documentation for that is hidden [here](https://aog.makie.org/v0.6/gallery/gallery/layout/nested_layouts/#Nested-layouts)).
- [ ] Document different data formats (pregrouped data documentation is hidden [here](https://aog.makie.org/dev/gallery/gallery/data%20manipulations/pre_grouped_data/#Pre-grouped-data), but it can be very useful for plots of 2D data such as heatmaps).

**Comment by jkrumbiegel** [comment]
I'm going to close this as the recent refactors touched a lot of these points, and if any of these points reappear it would be better to have targeted issues for them.
