### ISSUE TITLE
`stack` and `color` legend are in reverse order

### ISSUE THREAD

**Issue by ssfrr** [MakieOrg/AlgebraOfGraphics.jl#467]
## Bug description

The colors in the legend end up inverted from the blocks in a stacked bar chart, which makes it a little harder to scan.

## Steps to reproduce

```julia
using DataFrames
using AlgebraOfGraphics
using CairoMakie

df = DataFrame(x=repeat(1:3, 3), y = rand(9), z=["a", "a", "a", "b", "b", "b", "c", "c", "c"])
draw(data(df) * mapping(:x, :y; stack=:z, color=:z) * visual(BarPlot))
```

generates the plot:
<img width="542" alt="image" src="https://github.com/MakieOrg/AlgebraOfGraphics.jl/assets/734386/4ca16368-2d5c-4741-8026-283cdc21f5c4">

Notice the color ordering in the stacking and legend are reversed.

## Version info

AlgebraOfGraphics v0.6.16

**Comment by jkrumbiegel** [comment]
You can achieve reverse order now by passing `categories = reverse` to the `Stack` scale.

```julia
df = DataFrame(x=repeat(1:3, 3), y = rand(9), z=["a", "a", "a", "b", "b", "b", "c", "c", "c"])
draw(
    data(df) * mapping(:x, :y; stack=:z, color=:z) * visual(BarPlot),
    scales(Stack = (; categories = reverse))
)
```

<img width="581" alt="image" src="https://github.com/user-attachments/assets/020f3723-a72c-4939-8587-ebe312eee92a">

I agree that it makes for a more intuitive reading order, but on the other hand I think the process of stacking makes sense to think of as going bottom-up, also reverse order would work less well for horizontal barplots: 

<img width="581" alt="image" src="https://github.com/user-attachments/assets/29bd7132-bfe6-4d31-9e37-8a616a128ceb">

So I don't think I'm going to change the default here.
