### ISSUE TITLE
Title position when changing aspect for multiple-columns plot

### ISSUE THREAD

**Issue by apraga** [MakieOrg/AlgebraOfGraphics.jl#476]
## Bug description

Plot with multiple columns does not seem to move the title when aspect ratio is changed.

## Steps to reproduce

```
using CairoMakie, DataFrames
using AlgebraOfGraphics
d = DataFrame("type" => ["A", "A", "B", "B"], "category" => ["Cat1", "Cat2", "Cat1", "Cat2"], "value" => [1,1,2,3])

fig = data(d)*mapping(:type, :value, col=:category)*visual(BarPlot)
draw(fig; axis=(;aspect=2)) |> x -> save("test.png", x)
```

Using `titlegap` does not seem to move the title. Thanks !

## Images

The initial picture is fine 
![test-init](https://github.com/MakieOrg/AlgebraOfGraphics.jl/assets/914687/e398b00e-4911-477c-8510-9acb19c42d79)

But changing aspect ratio results in a large gap between title and plot
![test](https://github.com/MakieOrg/AlgebraOfGraphics.jl/assets/914687/9b6b28fe-35e3-42d0-afc4-2867ed2f4f3d)

## Version info

```
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, haswell)
  Threads: 1 on 8 virtual cores
```
Using latest Makie and AlgebraOfGraphics
```
  [cbdf2221] AlgebraOfGraphics v0.6.16
  [336ed68f] CSV v0.10.11
  [13f3f980] CairoMakie v0.10.12
  [a93c6f00] DataFrames v1.6.1
  [1313f7d8] DataFramesMeta v0.14.1
  [e9467ef8] GLMakie v0.8.12
  [cd3eb016] HTTP v1.10.0
  [1a8c2f83] Query v1.0.0

```

**Comment by jkrumbiegel** [comment]
This is not an AlgebraOfGraphics issue but related to Makie's behavior when using `aspect`. Further info can be found at https://docs.makie.org/stable/tutorials/aspect-tutorial
