### ISSUE TITLE
Density force the same xaxis on wide data plots with multiple variable

### ISSUE THREAD

**Issue by DarioSarra** [MakieOrg/AlgebraOfGraphics.jl#479]
I am trying to have a figure with the density plots of a variable and its log10 transform next to each other. I tried to pass the two variables as a string vector and call `col = dims(1)`. I obtain the plot, but the x-axis's span is the same for both plots, even if they have very different min and max values. I was expecting the two plots to have independent x-axis spans. I tried using `facet=(; linkxaxes=:none,)`, but it doesn't affect the result. It seems that the density was calculated taking the extrema from a combination of the 2 variables.

Here is an example:
```
v1 = rand(120)
v2 = log10.(v1)
testdf = DataFrame(v1 = v1,v2 = v2,cat = rand(["a","b","c"],120))
xvars = ["v1", "v2"]
plt = data(testdf) * AlgebraOfGraphics.density() * mapping(xvars, color = "cat", col = dims(1))
draw(plt, facet=(; linkxaxes=:none,))
```
![density_example](https://github.com/MakieOrg/AlgebraOfGraphics.jl/assets/25100449/c000afe2-7c8e-43d5-bc72-2dbc328e7267)

**Comment by jkrumbiegel** [comment]
You can pass `datalimits = extrema` to `density` to avoid this:

```julia
v1 = rand(120)
v2 = log10.(v1)
testdf = DataFrame(v1 = v1,v2 = v2,cat = rand(["a","b","c"],120))
xvars = ["v1", "v2"]
plt = data(testdf) * AlgebraOfGraphics.density(datalimits = extrema) * mapping(xvars, color = "cat", col = dims(1))
draw(plt, facet=(; linkxaxes=:none,))
```

<img width="524" alt="image" src="https://github.com/user-attachments/assets/b055ba44-d2a8-4a00-bc33-1a56239c186f">
