### ISSUE TITLE
histogram no longer works with line visual

### ISSUE THREAD

**Issue by Beforerr** [MakieOrg/AlgebraOfGraphics.jl#503]
## Bug description

Using `histogram` with `visual(Lines)` used to work, however after upgrading `Makie` or `AoG`, now it produces error.

## Steps to reproduce

Adapting the codes in the doc, the error is reproduced.

```
df = (x=randn(5000), y=randn(5000), z=rand(["a", "b", "c"], 5000))
specs = data(df) * mapping(:x, layout=:z) * histogram(bins=range(-2, 2, length=15)) * (visual(Lines))
draw(specs)
```

## Error reporting

`InvalidAttributeError: Invalid attributes dodge_gap, gap and width for plot type Lines.`

## Version info

  [cbdf2221] AlgebraOfGraphics v0.6.19
  [13f3f980] CairoMakie v0.12.2

**Comment by jkrumbiegel** [comment]
This worked before because Makie ignored invalid keyword arguments, which it doesn't anymore. Therefore I will close this issue as not actionable in AoG. A new issue or discussion could be opened if it's desired to add other plot primitives to `histogram`
