### ISSUE TITLE
Images missing from the Tutorial in the docs

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/AlgebraOfGraphics.jl#506]
From https://aog.makie.org/stable/generated/penguins/#Smooth-density-plots

the sections "smooth density plots" and "correlating three variables" are missing their first 3-4 images. Likely an error in the doc build. (probably a good idea to make Documetner.jl builds **error** if there is an error in the docbuild).

**Comment by jkrumbiegel** [comment]
This is not a build error, I think in recent Cairo something changed which makes certain vector graphics not show up in Firefox anymore, maybe other browsers, too. I checked Chrome and that did show those "blank" ones fine (although kind of laggy, so maybe it's about the size).

**Comment by jkrumbiegel** [comment]
Going to close this as not actionable for AoG, if at all it's a Makie issue if plots are not rendered well in certain browsers.
