### ISSUE TITLE
Define aesthetic mapping for crossbar

### ISSUE THREAD

**Issue by hendri54** [MakieOrg/AlgebraOfGraphics.jl#513]
## Problem description

AoG v0.7 currently does not support `crossbar` visual (previous versions did).
Calling `crossbar` results in an error:

`No aesthetic mapping defined yet for plot type Plot{Makie.crossbar} ...`

**Comment by jkrumbiegel** [comment]
fixed in https://github.com/MakieOrg/AlgebraOfGraphics.jl/pull/522
