### ISSUE TITLE
Add geom_raster and geom_sf-like features

### ISSUE THREAD

**Issue by Ujjwal4CULS** [MakieOrg/AlgebraOfGraphics.jl#577]
Could you please add features similar to geom_raster and geom_sf from ggplot2? This would greatly help in promoting Julia for geospatial visualization.

**Comment by jkrumbiegel** [comment]
Hi, thanks for your request! I think this is way too broad currently, I don't want to have to go and find out what these features are, how they compare to what we have, what is still missing. That info should be included in a feature request and it's better if feature requests are reasonably narrow. So I'm going to close this one but if you have more specific things with more background info, please open new issues for those.

**Comment by Ujjwal4CULS** [comment]
I think this request is too narrow. You have already provided these features partially; it just needs more specific details in the context of raster and .shp data.

**Comment by Jigyasu4indp** [comment]
You can add these features in Geometries (https://aog.makie.org/stable/gallery/gallery/applications/geometries/#Geometries) and Geographic data (https://aog.makie.org/stable/gallery/gallery/applications/geographic/#Geographic-data).
