### ISSUE TITLE
Legend disappears when adding plot into Makie figure

### ISSUE THREAD

**Issue by stelmo** [MakieOrg/AlgebraOfGraphics.jl#578]
Hi,

It looks like the legend is dropped when you embed an AoG plot into a Makie figure. See the example below:

```julia
using AlgebraOfGraphics, CairoMakie, DataFrames

df = DataFrame(X = rand(1:3, 100), Y = rand(100), G = rand(["1", "2"], 100))

plt = data(df) * visual(Violin) * mapping(:X, :Y, color=:G, side=:G)
draw(plt)
```
![Image](https://github.com/user-attachments/assets/a6dc0a83-ddfe-4c0e-a9ff-3a67c451da4f)

```julia
fig = Figure()
draw!(fig[1,1], plt)
fig
```
![Image](https://github.com/user-attachments/assets/fa13cf56-6321-45ea-92de-b14f4b6b074f)

**Comment by jkrumbiegel** [comment]
That's the documented behavior, you have to call `legend!` with the output of `draw!` to place the legend manually. It's assumed that in a larger figure you might want to put it somewhere else than usual.

**Comment by stelmo** [comment]
Ah okay, thanks for clearing it up! I just found it in the docs 😳 In case someone else lands here: https://aog.makie.org/stable/gallery/gallery/customization/legend/
